# Generated by Django 3.1.3 on 2020-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('empid', models.IntegerField(null=True)),
                ('presence', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinename', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Awaiting user', 'Awaiting user'), ('Under use', 'Under use'), ('Idle', 'Idle')], max_length=100, null=True)),
                ('worker', models.ManyToManyField(null=True, to='TVSapp.Worker')),
            ],
        ),
    ]
