# Generated by Django 3.1.3 on 2020-12-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='production',
            field=models.IntegerField(null=True),
        ),
    ]
