# Generated by Django 3.1.3 on 2020-12-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0002_machine_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='production',
            new_name='production_count',
        ),
        migrations.AlterField(
            model_name='machine',
            name='machinename',
            field=models.CharField(choices=[('Switches', 'Switches'), ('Solenoids', 'Solenoids'), ('Electro Mechanical Assemblies', 'Electro Mechanical Assemblies'), ('Computer Input Devices', 'Computer Input Devices'), ('Sensors', 'Sensors')], max_length=100, null=True),
        ),
    ]
