# Generated by Django 3.1.3 on 2020-12-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0003_auto_20201202_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='status',
        ),
    ]
