# Generated by Django 3.1.3 on 2020-12-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0004_remove_machine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='production_count',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='worker',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=10, null=True)),
                ('production_count', models.IntegerField(null=True)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TVSapp.machine')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TVSapp.worker')),
            ],
        ),
    ]
