# Generated by Django 3.1.3 on 2020-12-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0005_auto_20201202_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_count',
            field=models.IntegerField(null=True),
        ),
    ]
