# Generated by Django 3.1.3 on 2020-12-08 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0006_task_target_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='contact',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{9}$')]),
        ),
    ]
