# Generated by Django 3.1.3 on 2020-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0007_worker_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('Awaiting user', 'Awaiting user'), ('Idle', 'Idle'), ('Under use', 'Under use')], max_length=20, null=True),
        ),
    ]
