# Generated by Django 3.1.3 on 2020-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0008_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='qc_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='production_count',
            field=models.IntegerField(default=0),
        ),
    ]
