# Generated by Django 3.1.3 on 2020-12-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0009_auto_20201210_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
