# Generated by Django 3.1.3 on 2020-12-16 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0010_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 5, 45, 20, 596680, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
