# Generated by Django 3.1.3 on 2020-12-16 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0012_remove_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 11, 21, 20, 662004)),
            preserve_default=False,
        ),
    ]
