# Generated by Django 3.1.3 on 2020-12-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0013_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alloted_duration',
            field=models.IntegerField(default=0),
        ),
    ]
