# Generated by Django 3.1.3 on 2020-12-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0014_task_alloted_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='alloted_duration',
            new_name='allotted_duration',
        ),
    ]
