# Generated by Django 3.1.3 on 2020-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0015_auto_20201216_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
