# Generated by Django 3.1.3 on 2020-12-21 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVSapp', '0016_auto_20201216_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 16, 29, 6, 123020)),
        ),
    ]
